// idea
  var newAnalytics = new Analytics({
    id: parsedResponse.ID,
    title: parsedResponse.Title,
    time: parsedResponse.Time,
    numberOfExtractedIndicators: parsedResponse["Number of Extracted Indicators"],
    numberOfHitsWithIR: parsedResponse["Number of Hits with IR"],
    TotalEnrichmentFromOtherIRs: parsedResponse["TotalEnrichment from other IRs"],
    enrichmentFactor: parsedResponse["Enrichment Factor"],
    facebook_tx: parsedResponse["facebook-tx"],
    team_cymru: parsedResponse["team-crymru"],
    virustotal: parsedResponse.virustotal,
    rss_arstechnica: parsedResponse.rss_arstechnica,
    rss_cert: parsedResponse.rss_cert,
    rss_cisco: parsedResponse.rss_cisco,
    rss_debian: parsedResponse.rss_debian,
    rss_hotforsecurity: parsedResponse.rss_hotforsecurity,
    rss_infosecisland: parsedResponse.rss_infosecisland,
    rss_isc: parsedResponse.rss_isc,
    rss_krebsonsec: parsedResponse.rss_krebsonsec,
    rss_malwarebytes: parsedResponse.rss_malwarebytes,
    rss_mdl: parsedResponse.rss_mdl,
    rss_mmpc: parsedResponse.rss_mmpc,
    rss_ms_sec: parsedResponse.rss_ms_sec,
    rss_msrc: parsedResponse.rss_msrc,
    rss_nist: parsedResponse.rss_nist,
    rss_openbsd: parsedResponse.rss_openbsd,
    rss_packetstorm: parsedResponse.rss_packetstorm,
    rss_register: parsedResponse.rss_register,
    rss_slashdot: parsedResponse.rss_slashdot,
    rss_sucuri: parsedResponse.rss_sucuri,
    rss_symantec: parsedResponse.rss_symantec,
    rss_ubuntu: parsedResponse.rss_ubuntu,
    rss_unit42: parsedResponse.rss_unit42,
    rss_us_cert: parsedResponse["rss_us-cert"],
    rss_verizon: parsedResponse["rss_verizon"],
    rss_malwaremustdie: parsedResponse.rss_malwaremustdie
  });
  